name: veridata

services:
  veridata_sync:
    build:
      context: .
    container_name: veridata.sync
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@veridata.postgres:5432/${POSTGRES_DB}
    ports:
      - "${VERIDATA_SYNC_PORT:-8001}:8001"
    volumes:
      - .:/app
    networks:
      veridata.network:
        aliases:
          - veridata.sync
    env_file:
      - .env

networks:
  veridata.network:
    external: true
